### PR TITLE
code: cash register code of freecodecamp's js course

### PR DESCRIPTION
**Pull request by Daggron**

### CODE REVIEW

**Review by Yashank18 — CHANGES_REQUESTED** [review]
Can you make a folder with your name inside js directory so that it matches required rules?

**Comment by Daggron** [comment]
This is a bad hierarchy to make a folder of your name inside any folder and put your changes in that

**Comment by Daggron** [comment]
any ways updated the pr

**Review by Yashank18 — APPROVED** [review]
I understand your point, but there are a lot of beginners posting their code here and they get merge issues due to similarly named files.
Will update the whole repo with a better hierarchy :)

**Comment by Daggron** [comment]
For eg if I am searching a particular problem then I just type the problem name and see the result, but if the hierarchy of the folder is {name}/code then it impacts the SEO and reach of the code in a bad manner. No one would search abhay cash register code on google they will only search cash register problem, so this is backing the reach of the repo

**Pull request merged**
